### ISSUE TITLE
Not been working for a couple of weeks. so tried to remove and readd...

### ISSUE THREAD

**Issue by TheBartoMan** [gadget-man/iparcelboxHA#10]
Not been connecting for a few weeks. Checked everything. Now I have removed it and readded it and it won't add.

![image](https://github.com/user-attachments/assets/4f5c0139-8761-42c9-b822-221c18ca2009)

I see these errors:

Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
First occurred: 20:46:06 (2 occurrences)
Last logged: 20:55:06

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iparcelbox/config_flow.py", line 173, in async_step_link
    return await self.async_step_user(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iparcelbox/config_flow.py", line 146, in async_step_user
    if not status["result"]:
           ~~~~~~^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str

**Comment by gadget-man** [comment]
Please can you delete the component, restart HA then try adding back. Please confirm what version of HA you are currently running.

**Comment by TheBartoMan** [comment]
Evening,

I did try removing component and redownloading.

My version are:

•  Core 2024.12.5
•  Supervisor 2024.12.0
•  Operating System
•  Frontend 20241127.8

From: gadget-man ***@***.***>
Date: Tuesday, 24 December 2024 at 21:13
To: gadget-man/iparcelboxHA ***@***.***>
Cc: TheBartoMan ***@***.***>, Author ***@***.***>
Subject: Re: [gadget-man/iparcelboxHA] Not been working for a couple of weeks. so tried to remove and readd... (Issue #10)

Please can you delete the component, restart HA then try adding back. Please confirm what version of HA you are currently running.

**Comment by gadget-man** [comment]
Please could you email a copy of the HA logs from a reboot across to support@iparcelbox.com so we can take a look?

**Comment by TheBartoMan** [comment]
My initial issue was me being stupid! I was entering my password for the iParcelBox website, not the specific one for the box. Paul is kindly going to look at it giving a better error message.

My further issue was due to a config error. Under "Use Home Assistant Cloud" in HA Settings, it was unchecked and preventing me from checking it as I had some custom config in my configuration.yaml.

I temporarily removed this part of the config allowing me to turn on "Use Home Assistant Cloud"
