### ISSUE TITLE
Everything shows as unknown

### ISSUE THREAD

**Issue by TheBartoMan** [gadget-man/iparcelboxHA#2]
<img width="449" alt="Screenshot 2022-06-03 at 13 54 03" src="https://user-images.githubusercontent.com/28529964/171857970-c7b62dcc-22dd-4ef5-8096-11620b09c625.png">

**Comment by gadget-man** [comment]
This usually means it’s unable to get an update because the box is asleep. If your iParcelBox is awake, please can you check your HA logs to see if there are any errors showing?

**Comment by TheBartoMan** [comment]
when i click options such as "allow delivery" or "lock box" in the HA card,
i can see it makes the same happen on the iparcel iphone app - so it is
communicating.

I cant see any errors in the log. Do i need to enable them?

**Comment by gadget-man** [comment]
Please can you make a simulated delivery so that your iParcelBox is 'full', and then restart your HA instance and check the logs - it sounds as though the web hook is not receiving updates correctly even though action commands are being sent.

**Comment by TheBartoMan** [comment]
I cant add the box - i get this error
<img width="284" alt="Screenshot 2022-09-06 at 22 08 40" src="https://user-images.githubusercontent.com/28529964/188738871-ea74f323-d455-4b9d-b8e9-3661c44edd95.png">

**Comment by TheBartoMan** [comment]
<img width="567" alt="Screenshot 2022-09-06 at 22 12 18" src="https://user-images.githubusercontent.com/28529964/188739081-1dd0cf9a-718a-43b6-9a9a-aa88d97dc954.png">

**Comment by gadget-man** [comment]
Please could you reboot your HA instance and check the logs for any errors, also if you select 'configure' and enter your device password, do you get any specific messages in the logs?

**Comment by TheBartoMan** [comment]
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/iparcelbox/config_flow.py:145
Integration: Translation Error: The intl string context variable "host" was not provided to the string "iParcelBox {host}" (documentation)
First occurred: 6 September 2022 at 22:23:22 (2 occurrences)
Last logged: 17:07:27

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 172, in async_step_link
    return await self.async_step_user(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 145, in async_step_user
    if not status["result"]:
TypeError: tuple indices must be integers or slices, not str

**Comment by gadget-man** [comment]
Please can you download v0.0.12 and try again?

**Comment by TheBartoMan** [comment]
I updated and did a full reboot.. get this in the log when the i try to configure and it fails.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/iparcelbox/config_flow.py:146
Integration: iParcelBox (documentation)
First occurred: 18:06:23 (1 occurrences)
Last logged: 18:06:23

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 173, in async_step_link
    return await self.async_step_user(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 146, in async_step_user
    if not status.result:
AttributeError: 'tuple' object has no attribute 'result'

**Comment by gadget-man** [comment]
Please could you check further up in the logs - you should get a line saying `[custom_components.iparcelbox.config_flow] Got Status: XXXXX`. You may need to turn on debug logging in your configuration.yaml for the iParcelBox custom component.

**Comment by TheBartoMan** [comment]
Can you tell me the entries i require to turn on debog logging please?

**Comment by gadget-man** [comment]
logger:
  default: error
  logs:
    custom_components.iparcelbox: debug

**Comment by gadget-man** [comment]
Please can you also update to v0.0.13 and check again. At our end all seems to be OK - we're wondering if your iParcelBox is somehow reporting a rogue status (which should show up in the Status message).

**Comment by TheBartoMan** [comment]
Invalid domain custom_components.iparcelbox

**Comment by gadget-man** [comment]
Sorry the spacing / tabs were missing when I posted, try it like this:
![Screenshot 2022-09-07 at 18 52 33](https://user-images.githubusercontent.com/24406912/188945827-e3beaac2-4f12-4a5f-9853-14aaa1522e2d.png)

**Comment by TheBartoMan** [comment]
cleared all logs, rebooted, tried to configure ParcelBox.

This is all thats in the logs:-

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/iparcelbox/config_flow.py:146
Integration: iParcelBox (documentation)
First occurred: 19:00:05 (1 occurrences)
Last logged: 19:00:05

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 173, in async_step_link
    return await self.async_step_user(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 146, in async_step_user
    if not status["result"]:
TypeError: tuple indices must be integers or slices, not str

**Comment by gadget-man** [comment]
You should expect to see something similar to the below in the boot logs as your HA instance restarts. If not, there must be some error in your configuration. 
![Screenshot 2022-09-07 at 19 15 06](https://user-images.githubusercontent.com/24406912/188949715-7814ab3a-a776-45de-8f48-fae95c27f5fd.png)

**Comment by TheBartoMan** [comment]
Here are the lines with the personal details replaced with xxxxxx

2022-09-07 19:21:39.044 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] iParcelBox device found via ZeroConf: iParcelBox-xxxxxxxx._iparcelbox._tcp.local.
2022-09-07 19:21:39.044 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Got hostname from ZeroConf: xxx.xxx.xxx.xxxx
2022-09-07 19:21:39.044 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form
2022-09-07 19:22:11.302 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form
2022-09-07 19:22:21.750 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_HOST: xxx.xxx.xxx.xxx
2022-09-07 19:22:21.750 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_SERIAL: xxxxxxxx
2022-09-07 19:22:21.750 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_MAC: xxxxxxxxxxxxxx
2022-09-07 19:22:21.750 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_NAME: iParcelBox-xxxxxxxx
2022-09-07 19:22:21.750 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_PASSWORD: xxxxxxxxxxxxxxxxxxx
2022-09-07 19:22:26.924 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Got Status: (False, 401)

**Comment by gadget-man** [comment]
Thank you. That suggests an authentication error rather than a problem with the HA integration - the status call is failing. Please contact us via the iParcelBox support channels and we can look into this for you further.

**Comment by TheBartoMan** [comment]
Thank you and really sorry for wasting your time. My initial instructions are a photograph and it appears apple did a poor job when i cut and paste the password. One character was incorrect although looked almost identical.

Its back now thank you

**Comment by gadget-man** [comment]
OK great, no problem. In which case we'll close this Issue.

**Comment by TheBartoMan** [comment]
I have fixed it now. I have home assistant installed in docker. I rebuilt the docker instance with the network direct to hostOn Tue, Jun 7, 2022 at 8:30,             gadget-man ***@***.***> wrote:
Please can you make a simulated delivery so that your iParcelBox is 'full', and then restart your HA instance and check the logs - it sounds as though the web hook is not receiving updates correctly even though action commands are being sent.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gadget-man/iparcelboxHA/issues/2#issuecomment-1148300329",
"url": "https://github.com/gadget-man/iparcelboxHA/issues/2#issuecomment-1148300329",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
