### ISSUE TITLE
Discovery not completed

### ISSUE THREAD

**Issue by JanWitvrouwen** [gadget-man/iparcelboxHA#3]
In the logs, i find that my iparcelbox is discoverd but it results in the error underneath.
In the debug log form zerconf, i see incoming messages from the iparcelbox IP (on wich i can succesfully log in to the rpc status page)
```
2022-08-01 10:11:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 175, in async_step_zeroconf
    _LOGGER.debug("iParcelBox device found via ZeroConf: %s", info["name"])
TypeError: 'ZeroconfServiceInfo' object is not subscriptable
```

I'm running:
Home Assistant 2022.7.7 
Supervisor 2022.07.0 
Operating System 8.4
iParcelBox v0.0.9

**Comment by gadget-man** [comment]
We have pushed release v0.0.10 with additional logging added for config_flow.py. Please could you update your integration, reboot HA then try again and advise on any new logging?

**Comment by gadget-man** [comment]
Please could you test v0.0.11 and advise whether this solves the issue?

(Hold that thought - found another issue!)

**Comment by gadget-man** [comment]
OK, v0.0.11 should be working - please can you test and confirm?

**Comment by JanWitvrouwen** [comment]
Great succes!
