### ISSUE TITLE
Cannot add iparcelbox

### ISSUE THREAD

**Issue by JanWitvrouwen** [gadget-man/iparcelboxHA#4]
when adding manualy the iparcelbox, it reports that the password is incorrect or that the device is not online.
As i connected to the RPC status page moments before, i'm certain that the device is online and the password is correct.

I cant find any error in the logs.
I'm running:
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
iParcelBox v0.0.9

Maybe related to the non-discovery of the same device in the same setup as reported #3

**Comment by gadget-man** [comment]
Please could you set debugging of the iparcelbox component to debug or greater, then reboot your HA instance, try the connection again and share any relevant logs, so that we can try and understand what may be happening?

**Comment by JanWitvrouwen** [comment]
```
logger:
  default: WARNING
  logs:
    iparcelbox: debug
    custom_components.iparcelbox: debug
```

```
2022-08-02 19:26:21 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 175, in async_step_zeroconf
    _LOGGER.debug("iParcelBox device found via ZeroConf: %s", info["name"])
TypeError: 'ZeroconfServiceInfo' object is not subscriptable
2022-08-02 19:33:04 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form
2022-08-02 19:33:31 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_HOST: iParcelBox-188199008
2022-08-02 19:33:31 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_SERIAL: 188199008
2022-08-02 19:33:31 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_MAC: E0E2E6BCC708
2022-08-02 19:33:31 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_NAME: iParcelBox-188199008
2022-08-02 19:33:31 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_PASSWORD: NOTMYREALPASSWORD
2022-08-02 19:33:34 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form

```

**Comment by gadget-man** [comment]
Other than the `TypeError` which isn't a significant issue, all looks to be operating as expected. Do you ever see the setup form? Can you post a screenshot of your `Integrations` page in HA showing the discovered device, and confirm what happens when you click on it?

**Comment by JanWitvrouwen** [comment]
The device is not discovered either and doesnt show up under the Integrations, see issue #3 
With the version pushed to 0.0.10, the debug is exactly the same.

Is see the form and can enter the details. 
After submitting, this is the error.
![image](https://user-images.githubusercontent.com/26582003/182459799-37bb75b2-4acb-4f7d-993a-ce4c25a41978.png)

**Comment by gadget-man** [comment]
That is strange, as the line `_LOGGER.debug("iParcelBox device found via ZeroConf: %s", info["name"])` has now been removed from v0.0.10. Are you sure it's correctly updated on your machine?

**Comment by JanWitvrouwen** [comment]
It is v0.0.10 and you are right, it is not 100% the same. that string was not there.
```
2022-08-02 21:36:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/iparcelbox/config_flow.py", line 179, in async_step_zeroconf
    hostname = info["host"]
TypeError: 'ZeroconfServiceInfo' object is not subscriptable
2022-08-02 21:38:11 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form
2022-08-02 21:38:26 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form
2022-08-02 21:39:06 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_HOST: iParcelBox-188199008
2022-08-02 21:39:06 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_SERIAL: 188199008
2022-08-02 21:39:06 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_MAC: E0E2E6BCC708
2022-08-02 21:39:06 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_NAME: iParcelBox-188199008
2022-08-02 21:39:06 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] CONF_PASSWORD: XXXXX
2022-08-02 21:39:09 DEBUG (MainThread) [custom_components.iparcelbox.config_flow] Showing Setup Form
```

**Comment by gadget-man** [comment]
Many thanks, we’ve now been able to replicate the issue. It seems there was a breaking change in a recent HA update that we’d missed. We’re working on an update and will confirm as soon as it’s released.

**Comment by JanWitvrouwen** [comment]
V0. 0.11 also solved this.

Thanks for the support!
