### ISSUE TITLE
Since upgrade to latest HA, I have had issues with iParcelbox, showing as connected, but all "unknown" status

### ISSUE THREAD

**Issue by Jaw0lf** [gadget-man/iparcelboxHA#5]
First I want to say thank you very much for creating this addon.
I have been using this with my HA  setup and great to have my Alexas announce when a delivery is made!

Now I am having issues since the latest update of HA and am hoping that you can help me with this.

I ran the debug logging and found this section.

2023-04-28 11:59:55.512 ERROR (MainThread) [custom_components.iparcelbox.config_flow] TimeoutError connecting to iParcelBox at 192.168.5.19 ()

2023-04-28 12:05:58.513 INFO (MainThread) [homeassistant.setup] Setting up iparcelbox
2023-04-28 12:05:58.514 INFO (MainThread) [homeassistant.setup] Setup of domain iparcelbox took 0.0 seconds
2023-04-28 12:06:03.554 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for iparcelbox using this method at custom_components/iparcelbox/__init__.py, line 114: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
2023-04-28 12:06:03.561 INFO (MainThread) [homeassistant.components.lock] Setting up lock.iparcelbox
2023-04-28 12:06:03.562 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.iparcelbox
2023-04-28 12:06:03.571 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.iparcelbox
2023-04-28 12:06:03.581 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new lock.iparcelbox entity: lock.iparcelbox

It continues to find sensors and binary_sensors for the rest of the entities.

Hope this information is sufficient. I am using the latest version 0.0.13

Thank you

**Comment by gadget-man** [comment]
Please can you confirm what version of HA you're running? Here we're on 2023.4.6 and aren't getting that error in the logs.
Also, if you've got a battery-powered iParcelBox, it may be asleep so unable to update the data in HA - press the button on the box to wake it up, and see if that corrects the issue.

**Comment by gadget-man** [comment]
I've also now pushed an update (v0.0.14) which should correct the specific error message you were receiving. I'd be grateful if you would check and confirm it now works again?

**Comment by Jaw0lf** [comment]
Home Assistant 2023.4.6 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230411.1 - latest 

I have just removed the device, then deleted the Custom Integration from within HACS, restarted, downloaded updated v0.0.14 rerstarted and logged in. It still shows unknown states. Restarted the iParcelbox addin. Then got this error....

Mine is an original iParcelbox with no battery.

Logger: homeassistant.config_entries
Source: components/webhook/__init__.py:46
First occurred: 20:44:34 (1 occurrences)
Last logged: 20:44:34

Error setting up entry iParcelBox-(BoxNumber) for iparcelbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/iparcelbox/__init__.py", line 138, in async_setup_entry
    webhook.async_register(
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 46, in async_register
    raise ValueError("Handler is already defined!")
ValueError: Handler is already defined!

**Comment by Jaw0lf** [comment]
Tried reloading again and I also have an extra set of information for an error

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:169
First occurred: 20:50:22 (6 occurrences)
Last logged: 21:11:17

Error setting up entry iParcelBox-xxxxxx for lock
Error setting up entry iParcelBox-xxxxxx for sensor
Error setting up entry iParcelBox-xxxxxx for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 122, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by gadget-man** [comment]
Ok that looks as though it's somehow trying to add the device twice and getting stuck. I'm assuming that after reloading, the device is being auto-discovered?  We'll try and replicate the issue at our end and get back to you.

**Comment by gadget-man** [comment]
We’re unable to replicate the issue at our end. There are a few things we’d like to try with you. When convenient, please can you contact customer support chat, either via the app or on our website?

**Comment by Jaw0lf** [comment]
It seems a couple of issues may have been cause of this. 
iParcel box device was not deleting, had to manually delete from .storage
Then enabled debug and saw all forwarding to my domain on :8123
Checks showed this not working so fixed in my router, whilst also requesting a delivery in the app. One or both of these started to update my iParcelbox device statistics.

**Comment by gadget-man** [comment]
Worth noting that the 'Handler is already defined!' error was unrelated, a bug we identified when an already installed device was reloaded. This is fixed in v0.0.15.
