### ISSUE TITLE
ValueError: could not convert string to float: 'unknown'

### ISSUE THREAD

**Issue by pgale** [gadget-man/iparcelboxHA#7]
Got this on an HA restart after installing the integration yesterday.

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:575
First occurred: 08:13:09 (6 occurrences)
Last logged: 08:13:13

Error while processing template: Template<template=({% set state=states('sensor.iparcelbox_parcelcount')|float %} {% if state == 0 %} none {% else %} red {% endif %}) renders=2>
Error while processing template: Template<template=({% set state=states('sensor.iparcelbox_parcelcount')|float %} {% if state == 0 %} none {% else %} mdi:exclamation {% endif %}) renders=2>
Error while processing template: Template<template=({% set state=states('sensor.iparcelbox_parcelcount')|float %} {% if state == 0 %} light-grey {% else %} light-green {% endif %}) renders=6>
Error while processing template: Template<template=({% set state=states('sensor.iparcelbox_parcelcount')|float %} {% if state == 0 %} none {% else %} red {% endif %}) renders=6>
Error while processing template: Template<template=({% set state=states('sensor.iparcelbox_parcelcount')|float %} {% if state == 0 %} none {% else %} mdi:exclamation {% endif %}) renders=6>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2037, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 573, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2364, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2040, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1668, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set state=states('sensor.iparcelbox_parcelcount')|float %}
{% if state == 0 %} light-grey
{% else %} light-green
{% endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 699, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 575, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set state=states('sensor.iparcelbox_parcelcount')|float %}
{% if state == 0 %} light-grey
{% else %} light-green
{% endif %}' but no default was specified
```

**Comment by gadget-man** [comment]
I don't recognise this code from the iParcelBox integration. Reference in the code above is to helpers. Please can you check your defined helper entities under settings > Devices & services > Helpers. Have you created one associated with iParcelBox?

**Comment by pgale** [comment]
Ok that's odd. I haven't created any helpers related to iParcelBox. Unless there's some integration doing something with them but there's nothing showing.

**Comment by pgale** [comment]
In this context, isn't helpers referring to something else and not HA helpers such as toggle etc?

**Comment by gadget-man** [comment]
I can't find anything close to the code referenced in the errors in either the iParcelBox integration or the card. Are you including details on the iParcelBox parcel count anywhere else on any Lovelace dashboards?

**Comment by gadget-man** [comment]
Please can you confirm whether you are still having this issue or if it can be closed?

**Comment by pgale** [comment]
Yes still see it on restarting HA. Doesn't seem to stop the integration from working though.

**Comment by pgale** [comment]
To answer your earlier question - I use a copy of the card on one dashboard and in that same dashboard, I have a mushroom template card button that shows a badge icon based on the parcelcount. That dashboard is permanently displayed on an nspanel pro device. I don't think this appears anywhere else.

**Comment by gadget-man** [comment]
> To answer your earlier question - I use a copy of the card on one dashboard and in that same dashboard, I have a mushroom template card button that shows a badge icon based on the parcelcount. That dashboard is permanently displayed on an nspanel pro device. I don't think this appears anywhere else.

Ok that's almost certainly the issue. Please can you share the yaml for the mushroom template - I suspect the issue is that it's trying to render iParcelBox Count which you've defined as a float but during the setup process it may return as 'unknown' which is giving you the error.

**Comment by pgale** [comment]
Yes I was wondering about something like that. This is the code - It's within a grid card:

```
 - type: custom:mushroom-template-card
    entity: sensor.iparcelbox_parcelcount
    primary: Parcel
    secondary: Box
    icon: mdi:package-variant
    icon_color: |-
      {% set state=states('sensor.iparcelbox_parcelcount')|float %}
      {% if state == 0 %} light-grey
      {% else %} light-green
      {% endif %}
    tap_action:
      action: navigate
      navigation_path: '#parcel'
    hold_action:
      action: none
    double_tap_action:
      action: none
    badge_icon: |-
      {% set state=states('sensor.iparcelbox_parcelcount')|float %}
      {% if state == 0 %} none
      {% else %} mdi:exclamation
      {% endif %}
    badge_color: |-
      {% set state=states('sensor.iparcelbox_parcelcount')|float %}
      {% if state == 0 %} none
      {% else %} red
      {% endif %}
    card_mod:
      style:
        mushroom-state-info$: |
          .container {
           --card-primary-font-size: 20px;
           --card-secondary-font-size: 18px;
           --card-primary-line-height: 20px !important ;
           --card-secondary-line-height: 20px !important ;           
          }
        .: |
          ha-card {
            height: 95px !important;
            padding-bottom: 10px !important;
            padding-top: 10px !important;
          }
```

**Comment by gadget-man** [comment]
Ok that's your issue - nothing to do with the iParcelBox card. You have this code in the template:
`{% set state=states('sensor.iparcelbox_parcelcount')|float %}`
That will fail if `sensor.iparcelbox_parcelcount` cannot be converted to a float (e.g. if it's reporting as unknown, which it will be on loading HA).

**Comment by pgale** [comment]
ok - will look at modifying that then.
